### PR TITLE
removed all the empty else condition

### PR DESCRIPTION
**Pull request by d78ui98**
I made simple code optimization by removing all the empty else condition.
This can reduce the number of lines of code from `1680` to `1322`

### CODE REVIEW

**Comment by rebootuser** [comment]
This makes a lot of sense, I appreciate the work. I'll run some checks to ensure everything works as expected (can't see why it shouldn't) and will merge when verified.

**Comment by d78ui98** [comment]
Sure. Feel free to run the tests :)

**Comment by rebootuser** [comment]
Code has been updated since this pull (I have been slow to commit this, apologies). If you can update the request, I'll commit changes. Alternatively, I'm happy to make changes and reference your contribution.

**Comment by d78ui98** [comment]
@rebootuser I have updated the request and tested it.
> Alternatively, I'm happy to make changes and reference your contribution.

That would be great!

**Comment by rebootuser** [comment]
Merged. This is a great contribution, very much appreciate your efforts in cleaning up the code!

**Pull request merged**
