### PR TITLE
WIP sort files by modified date

### PR DESCRIPTION
**Pull request by tehmoon**
Following #32, this is first draft of the implementation.
@rebootuser I would like to draw your attention to the following:

- Arrays are not supported for `dash` which is a symlink for `/bin/sh` on some distributions
- I am not sure I like the syntax: ```wwsgidrt=`find / -uid 0 -perm -2007 -type f "${find_sort_print_flag[@]}" -exec ls -la {} 2>/dev/null \; | eval "${find_sort_pipe_args}"``` because it adds complexity
- I had to get rid of the syntax: ```find /etc/init.d/ \! -uid 0 -type f 2>/dev/null |xargs -r ls -la 2>/dev/null``` to make it work with the rest

It is not yet done, but I would like your review before proceeding, in case I have to find another alternative.

The result works as expected:

For `find` based commands:
```[-] SGID files:
-rwxr-sr-x 1 root shadow 22808 Jan 25 2018 /usr/bin/expiry
-rwxr-sr-x 1 root shadow 71816 Jan 25 2018 /usr/bin/chage
-rwxr-sr-x 1 root shadow 34816 Apr 5 2018 /sbin/pam_extrausers_chkpwd
-rwxr-sr-x 1 root shadow 34816 Apr 5 2018 /sbin/unix_chkpwd
-rwxr-sr-x 1 root tty 30800 Jul 26 2018 /usr/bin/wall
```

For `ls` based commands:
```
[-] /etc/init.d/ binary permissions:
total 16
-rwxr-xr-x 1 root   root    1191 Jan 17  2018 procps
-rwxr-xr-x 1 root   root    3809 Feb 14  2018 hwclock.sh
drwxr-xr-x 1 root   root    4096 Mar 25 16:24 ..
-rw-r--r-- 1 nobody nogroup    0 Mar 25 17:59 toto
-rw-r--r-- 1 nobody nogroup    0 Mar 25 17:59 tota
drwxr-xr-x 1 root   root    4096 Mar 25 17:59 .
```

Thank you for your time and input!

### CODE REVIEW

**Comment by tehmoon** [comment]
Ok I found another way of doing this that will be portable.

**Comment by tehmoon** [comment]
@rebootuser The code looks way cleaner and I tested it with `dash` and `bash`. I also tested on an `ubuntu` container and with `alpine`.
It does not appear to work well with `busybox`'s `find` since there is no `printf`. If that's a requirement, I'll try to make it work, by detecting the `find` version.

**Comment by tehmoon** [comment]
@rebootuser OK I think I'm finally done and happy with the result. It works on:

- `bash` and I assume other modern shells
- `dash` default `/bin/sh` on `ubuntu`
- `alpine find` or `busybox` based systems (de-active the `printf` option)

**Comment by rebootuser** [comment]
Apologies for the delayed reply and thanks for the additions! I'll test these out and revert shortly.

**Comment by tehmoon** [comment]
No worries at all! I'm here if you have any questions.

**Comment by rebootuser** [comment]
Firstly, I appreciate the contribution. Looking at the additions it seems that a level of complexity has been introduced and I'm not sure that the benefits are great enough to outweigh the need for this functionality. My main concern is compatibility with a large range of shells/distos.

**Comment by tehmoon** [comment]
Hi! Thank you for making such an awesome script!

Yes, that's the only way I found that would be as portable as possible. I use it every day and I've been trying to fix as many things as possible whenever I see a glitch.

I totally understand though. Don't hesitate to give it a try and see if it helps you! I'll keep the branch open and up to date with upstream because it does really help me.

If you have any ideas on how to make it better, let me know!

**Comment by rebootuser** [comment]
Closing for now as I think this introduces a level of complexity that *might* cause issues on some distos. Your contribution is very much appreciated, and in downtime I'll try to test this further.

**Comment by tehmoon** [comment]
Thank you for at least looking into it and considering it! I'm keeping my fork up at https://github.com/tehmoon/LinEnum just in case! (Also because I'm using it)

**Pull request closed without merging**
